### ISSUE TITLE
Error: EACCES: permission denied, open './stdout.log'

### ISSUE THREAD

**Issue by saydulk** [w3f/polkadot-deployer#11] opened 2019-06-26 23:07 UTC
I am using ubuntu 18.04 LTS 64 bit Linux.
![Screenshot from 2019-06-27 05-04-41](https://user-images.githubusercontent.com/1058663/60220896-6301ee80-9899-11e9-89d5-d90a14d2f7a7.png)
![Screenshot from 2019-06-27 05-04-07](https://user-images.githubusercontent.com/1058663/60220902-67c6a280-9899-11e9-915f-6d57527fdba9.png)

node -v: v10.16.0
npm -v: 6.9.0

After run : sudo npm i -g polkadot-deployer

root@tellus-merchant:/var/www/polkadot-deployer# sudo npm i -g polkadot-deployer
/usr/bin/polkadot-deployer -> /usr/lib/node_modules/polkadot-deployer/index.js

> secp256k1@3.7.1 install /usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
  stack:
   'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> secp256k1@3.7.1 rebuild /usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1/.node-gyp'
gyp ERR! System Linux 4.15.0-52-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> ursa-optional@0.9.10 install /usr/lib/node_modules/polkadot-deployer/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.<anonymous> (/usr/lib/node_modules/polkadot-deployer/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.9.10 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.9.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-26T23_03_53_352Z-debug.log

**Comment by fgimenez** [comment] 2019-06-27 07:25
Hi @saydulk thanks for reporting!!

You should be able to execute without sudo, just `npm i -g polkadot-deployer` should be enough.

If that doesn't work for you maybe there are issues with your node installation. You can either try something like nvm https://github.com/nvm-sh/nvm to manage isolated node installations or try to fix the permissions problem in your installation with https://github.com/nvm-sh/nvm/issues/1407#issuecomment-316858947 (this can lead to further problems though).

Let me know how it goes, cheers.

**Comment by saydulk** [comment] 2019-06-27 23:02
@fgimenez thanks it works. Now when i run $ sudo polkadot-deployer create
its shows:

? Enter the new deployment name: masum
? Deployment type: local
? Number of Polkadot nodes (1-200): 11
Creating cluster 'masum'...
Command execution failed with code: 1
Could not create local deployment: 1
Could not create cluster: 1
Command execution failed with code: 1
Could not delete local deployment: 1
![Screenshot from 2019-06-28 05-01-18](https://user-images.githubusercontent.com/1058663/60306385-c6575380-9961-11e9-8414-615c8f38e83d.png)
 
cheers

**Comment by fgimenez** [comment] 2019-06-28 08:00
You can execute with the `--verbose` flag to get more info about what is going on:
```
$ sudo polkadot-deployer create --verbose
```
Also, in order to make things easier, you can create a json configuration file and pass it to the create command with the `-c` flag:
```
$ cat <<EOF > cfg.json
{
  "name": "massum",
  "type": "local",
  "nodes": 111
}
EOF
$ sudo polkadot-deployer create -c ./cfg.json --verbose
```

**Comment by fgimenez** [comment] 2019-07-15 07:28
@saydulk closing for now as i can't reproduce, feel free to reopen.

**Closed by fgimenez** 2019-07-15 07:28 UTC

**Comment by soc1c** [comment] 2019-07-15 08:35
Having the same issue on Archlinux. @fgimenez 

Without superuser:

```bash
❯ npm i -g polkadot-deployer 
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, access '/usr/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-07-15T08_32_08_579Z-debug.log

~ 19s
```

With escalated privileges:

```bash
❯ sudo npm i -g polkadot-deployer
[sudo] password for user: 
/usr/bin/polkadot-deployer -> /usr/lib/node_modules/polkadot-deployer/index.js

> secp256k1@3.7.1 install /usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, scandir '/root/.npm/_logs'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
  stack:
   "Error: EACCES: permission denied, scandir '/root/.npm/_logs'",
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> secp256k1@3.7.1 rebuild /usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/root/.cache/node-gyp/11.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1/.node-gyp'
gyp ERR! System Linux 5.1.16-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/polkadot-deployer/node_modules/secp256k1
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> ursa-optional@0.9.10 install /usr/lib/node_modules/polkadot-deployer/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:119
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:448:3)
    at Object.writeFileSync (fs.js:1210:35)
    at Object.<anonymous> (/usr/lib/node_modules/polkadot-deployer/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/polkadot-deployer/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.9.10 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.9.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-15T08_33_39_527Z-debug.log

~ 33s
```

But with root I should be able to read it:

```bash
❯ sudo ls -lsha /root/.npm/_logs
total 2.8M
4.0K drwxr-xr-x 2 root root 4.0K Jul 15 10:33 .
4.0K drwxr-xr-x 5 root root 4.0K Jul 15 10:27 ..
764K -rw-r--r-- 1 root root 763K Jul 15 10:27 2019-07-15T08_27_27_613Z-debug.log
688K -rw-r--r-- 1 root root 685K Jul 15 10:29 2019-07-15T08_29_59_569Z-debug.log
688K -rw-r--r-- 1 root root 686K Jul 15 10:30 2019-07-15T08_30_50_808Z-debug.log
688K -rw-r--r-- 1 root root 685K Jul 15 10:33 2019-07-15T08_33_39_527Z-debug.log

~
❯ node --version
v11.15.0

~
❯ npm --version
6.10.1

~
❯ uname -a
Linux alcor 5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64 GNU/Linux
```

Node 11.15.0, NPM 6.10.1, Archlinux kernel 5.1.16

**Comment by fgimenez** [comment] 2019-07-15 08:41
@soc1c This issue doesn't seem related to polkadot-deployer, but to the specific npm config you have, which prevents a non-root user to install packages globally. Take a look at https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally to solve it.

**Comment by soc1c** [comment] 2019-07-15 09:19
node is such a mess. thanks.

**Comment by johnhckuo** [comment] 2021-08-05 11:51
still have the same issue in 2021. *sigh*
